name: advent_of_code
description: A collection of my Advent of Code answers
version: 0.0.1
repository: https://github.com/theskyblockman/advent_of_code

environment:
  sdk: ^3.7.0-41.0.dev

dependencies:
  args: ^2.5.0
  logging: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
